
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-11T01:36:44.419Z
 * Generated source version: 3.6.4
 *
 */
public final class ConsultationUtility_ConsultationUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://default_package/", "ConsultationUtilityService");

    private ConsultationUtility_ConsultationUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultationUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ConsultationUtilityService ss = new ConsultationUtilityService(wsdlURL, SERVICE_NAME);
        ConsultationUtility port = ss.getConsultationUtilityPort();

        {
        System.out.println("Invoking registarUser...");
        java.lang.String _registarUser_arg0 = "_registarUser_arg0-1231829366";
        java.lang.String _registarUser_arg1 = "_registarUser_arg1-192861043";
        java.lang.String _registarUser__return = port.registarUser(_registarUser_arg0, _registarUser_arg1);
        System.out.println("registarUser.result=" + _registarUser__return);


        }
        {
        System.out.println("Invoking updateConsulta...");
        int _updateConsulta_arg0 = 792019790;
        java.lang.String _updateConsulta_arg1 = "_updateConsulta_arg1-1673433673";
        int _updateConsulta_arg2 = -895220860;
        java.lang.String _updateConsulta__return = port.updateConsulta(_updateConsulta_arg0, _updateConsulta_arg1, _updateConsulta_arg2);
        System.out.println("updateConsulta.result=" + _updateConsulta__return);


        }
        {
        System.out.println("Invoking cancelarConsulta...");
        int _cancelarConsulta_arg0 = 1866781878;
        int _cancelarConsulta_arg1 = -1476447527;
        java.lang.String _cancelarConsulta__return = port.cancelarConsulta(_cancelarConsulta_arg0, _cancelarConsulta_arg1);
        System.out.println("cancelarConsulta.result=" + _cancelarConsulta__return);


        }
        {
        System.out.println("Invoking listarConsultas...");
        int _listarConsultas_arg0 = 2049392401;
        java.util.List<java.lang.String> _listarConsultas__return = port.listarConsultas(_listarConsultas_arg0);
        System.out.println("listarConsultas.result=" + _listarConsultas__return);


        }
        {
        System.out.println("Invoking loginUser...");
        java.lang.String _loginUser_arg0 = "_loginUser_arg01645753666";
        java.lang.String _loginUser_arg1 = "_loginUser_arg11178584597";
        java.util.List<java.lang.String> _loginUser__return = port.loginUser(_loginUser_arg0, _loginUser_arg1);
        System.out.println("loginUser.result=" + _loginUser__return);


        }
        {
        System.out.println("Invoking reservarConsulta...");
        java.lang.String _reservarConsulta_arg0 = "_reservarConsulta_arg01156297523";
        java.lang.String _reservarConsulta_arg1 = "_reservarConsulta_arg1674252299";
        java.lang.String _reservarConsulta_arg2 = "_reservarConsulta_arg21015942240";
        int _reservarConsulta_arg3 = 333960865;
        java.lang.String _reservarConsulta__return = port.reservarConsulta(_reservarConsulta_arg0, _reservarConsulta_arg1, _reservarConsulta_arg2, _reservarConsulta_arg3);
        System.out.println("reservarConsulta.result=" + _reservarConsulta__return);


        }

        System.exit(0);
    }

}
