package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-11T01:36:44.656Z
 * Generated source version: 3.6.4
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "ConsultationUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultationUtility {

    @WebMethod(operationName = "RegistarUser")
    @RequestWrapper(localName = "RegistarUser", targetNamespace = "http://default_package/", className = "default_package.RegistarUser")
    @ResponseWrapper(localName = "RegistarUserResponse", targetNamespace = "http://default_package/", className = "default_package.RegistarUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String registarUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updateConsulta", targetNamespace = "http://default_package/", className = "default_package.UpdateConsulta")
    @ResponseWrapper(localName = "updateConsultaResponse", targetNamespace = "http://default_package/", className = "default_package.UpdateConsultaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String updateConsulta(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod
    @RequestWrapper(localName = "cancelarConsulta", targetNamespace = "http://default_package/", className = "default_package.CancelarConsulta")
    @ResponseWrapper(localName = "cancelarConsultaResponse", targetNamespace = "http://default_package/", className = "default_package.CancelarConsultaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String cancelarConsulta(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "listarConsultas", targetNamespace = "http://default_package/", className = "default_package.ListarConsultas")
    @ResponseWrapper(localName = "listarConsultasResponse", targetNamespace = "http://default_package/", className = "default_package.ListarConsultasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> listarConsultas(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://default_package/", className = "default_package.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://default_package/", className = "default_package.LoginUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.String> loginUser(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "reservarConsulta", targetNamespace = "http://default_package/", className = "default_package.ReservarConsulta")
    @ResponseWrapper(localName = "reservarConsultaResponse", targetNamespace = "http://default_package/", className = "default_package.ReservarConsultaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String reservarConsulta(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );
}
