package default_package;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-11T01:36:44.675Z
 * Generated source version: 3.6.4
 *
 */
@WebServiceClient(name = "ConsultationUtilityService",
                  wsdlLocation = "http://localhost:8080/ConsultationWebSOAP/services/ConsultationUtilityPort?wsdl",
                  targetNamespace = "http://default_package/")
public class ConsultationUtilityService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://default_package/", "ConsultationUtilityService");
    public static final QName ConsultationUtilityPort = new QName("http://default_package/", "ConsultationUtilityPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ConsultationWebSOAP/services/ConsultationUtilityPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultationUtilityService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ConsultationWebSOAP/services/ConsultationUtilityPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultationUtilityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultationUtilityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultationUtilityService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultationUtilityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultationUtilityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultationUtilityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultationUtility
     */
    @WebEndpoint(name = "ConsultationUtilityPort")
    public ConsultationUtility getConsultationUtilityPort() {
        return super.getPort(ConsultationUtilityPort, ConsultationUtility.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultationUtility
     */
    @WebEndpoint(name = "ConsultationUtilityPort")
    public ConsultationUtility getConsultationUtilityPort(WebServiceFeature... features) {
        return super.getPort(ConsultationUtilityPort, ConsultationUtility.class, features);
    }

}
