
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-12-11T01:36:44.624Z
 * Generated source version: 3.6.4
 *
 */

@javax.jws.WebService(
                      serviceName = "ConsultationUtilityService",
                      portName = "ConsultationUtilityPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://localhost:8080/ConsultationWebSOAP/services/ConsultationUtilityPort?wsdl",
                      endpointInterface = "default_package.ConsultationUtility")

public class ConsultationUtilityPortImpl implements ConsultationUtility {

    private static final Logger LOG = Logger.getLogger(ConsultationUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#registarUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String registarUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation registarUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1454524998";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#updateConsulta(int arg0, java.lang.String arg1, int arg2)*
     */
    public java.lang.String updateConsulta(int arg0, java.lang.String arg1, int arg2) {
        LOG.info("Executing operation updateConsulta");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return865496505";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#cancelarConsulta(int arg0, int arg1)*
     */
    public java.lang.String cancelarConsulta(int arg0, int arg1) {
        LOG.info("Executing operation cancelarConsulta");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return268683455";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#listarConsultas(int arg0)*
     */
    public java.util.List<java.lang.String> listarConsultas(int arg0) {
        LOG.info("Executing operation listarConsultas");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-141382143";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#loginUser(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.util.List<java.lang.String> loginUser(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation loginUser");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1 = "_returnVal-2010919590";
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.ConsultationUtility#reservarConsulta(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3)*
     */
    public java.lang.String reservarConsulta(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3) {
        LOG.info("Executing operation reservarConsulta");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return-156662536";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
